name: Update #1

on:
  push:
    branches: [ master ]
  schedule:
    - cron: "*/1 * * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Rename old README
      run: |
        mv README.md old_README.md
    - name: Generate new README
      env:
        LASTFM_API_KEY: ${{ secrets.LASTFM_API_KEY }}
        LASTFM_API_SECRET: ${{ secrets.LASTFM_API_SECRET }}
        LASTFM_USERNAME: ${{ secrets.LASTFM_USERNAME }}
        LASTFM_PASSWORD: ${{ secrets.LASTFM_PASSWORD }}
      run: |
        python main.py $LASTFM_API_KEY $LASTFM_API_SECRET $LASTFM_USERNAME $LASTFM_PASSWORD
    - name: Commit new README
      uses: EndBug/add-and-commit@v4
      with:
        add: 'README.md'
        author_name: Action
        author_email: action@github.com
        message: 'Action: Updated now playing'
        ref: 'master'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
